### ISSUE TITLE
Missing interactions for self hosted server

### ISSUE THREAD

**Issue by ehsandeep** [wdahlenburg/interactsh-collaborator#4]
- Load [latest](https://github.com/wdahlenburg/interactsh-collaborator/releases/tag/v1.0.1) jar file in burp
- Update with self-hosted server under config
- Click on Update settings
- Generate new payload
- Visit the URL, notice interactions are not updated.

**Comment by wdahlenburg** [comment]
Thanks for the quick update. I need to spin up a self-hosted server to verify.

**Comment by ehsandeep** [comment]
Sure @wdahlenburg, if it helps you can also use `hackwithautomation.com` for testing.

**Comment by wdahlenburg** [comment]
Hi @ehsandeep. I just set up a self-hosted server and am able to get interactions for DNS, HTTP, and SMTP. I didn't make any code changes from ad3f987.

The server you provided requires an authorization header, which means you should have something like `-auth -token password` in you server command. Can you email me or send me a DM on twitter with the authorization header value for that server and I can try to troubleshoot from my side?

**Comment by ehsandeep** [comment]
@wdahlenburg, you are right, it was running with dev branch and also with a token, I've rested and can confirm it works well with self-hosted server as well self-hosted + authorization header.

I can only suggest not updating the server value if the registration is not successful.

**Comment by wdahlenburg** [comment]
Thanks for double checking. I'm going to re-release v1.0.1.

The server settings are currently used at time of registration. A dummy client could be used to test if the server settings work. I think I'd prefer to see a /health endpoint or something on the servers that can verify authentication and that the server is running.

I'd also like to have a popup occur if the registration fails so that users aren't completely aware of the failure. Right now users need to check the logs for any errors.

**Comment by ehsandeep** [comment]
Closing as no changes are required, thank you for checking.
